### ISSUE TITLE
macOS desktop client can interfere with keyboard input and prevent typing accented characters.

### ISSUE THREAD

**Issue by SergeantConfused** [bitwarden/desktop#1041]
## Describe the Bug
When booting up the machine and keeping the Bitwarden macOS desktop client locked in the background, long pressing E or U results in repeatedly typing the same character. After opening and unlocking the Bitwarden desktop client, long pressing E or U opens the menu that allows you to select an accented version.

## Steps To Reproduce
1. Install the Bitwarden macOS desktop client from the Mac App Store.
2. Activate the following in its preferences:
_A. Unlock with Touch ID
B. Enable menu bar icon
C. Minimize to menu bar
D. Close to menu bar
E. Start to menu bar
F. Start automatically on login_
3. Reboot the machine.
4. Once it's booted back up, open Notes and long press the letter E.

## Expected Result
To see the accented character selection menu.

## Actual Result
The letter E is typed repeatedly.

## Screenshots or Videos
Internal.

## Environment
- Operating system: macOS 11.5.2.
- Installation method: Mac App Store.
- Build Version: 1.27.1.

## Additional Context
This reportedly also affects the input when using the computer keyboard as a musical keyboard in Ableton Live (https://en.wikipedia.org/wiki/Ableton_Live); it turns a single long musical note into a succession of repeating notes.

**Comment by eliykat** [comment]
@SergeantConfused I suspect this is a duplicate of #298, which is fixed in the latest release. Please ask the customer to update to 1.28.x and see if the problem is solved.

**Comment by PatrickBK** [comment]
In the App Store, the latest version is 1.27.1 and there is no reference anywhere in the desktop app to another update procedure nor is there mention of a version number on the site so where is this new version?





Met vriendelijke groet/sincerely,

Patrick Bos Kessen

	+31 629 006 722

**Comment by PatrickBK** [comment]
Btw.

Downloading Bitwarden for MacOS from the link on  your site leads to the version you refer to but leaves me without Bitwarden support in Safari which is what I mainly use Bitwarden for.

Bitwarden is no longer in Safari and to get it there I have to install it from the App storer which I can’t do since it’s installed already and I have to remove the version you refer to, to be able to install it into Safari from the Appstore.

Please tell me how this makes things better for me? ;-) For now I’m removing the version you refer to and reinstalling the version from the App Store.

A password manager that doesn’t work in my preferred webbrowser is a rather useless thing so please advise on a solution that actually works and doesn’t make the whole thing a lame duck ;-)

Oh and test, the version you refer to does seem to fix the special character bug so how great would things be if it were to become the complete solution it should be.

Met vriendelijke groet/sincerely,

Patrick Bos Kessen

	+31 629 006 722

**Comment by eliykat** [comment]
Hi @PatrickBK, sorry I forgot to check whether the latest release was available on the App Store yet. It can sometimes take a week or so to get approved by Apple. However, we submit it for approval as part of our release process, so it shouldn’t be too far away. 

If installing the latest version via our website is just causing more issues for you, please stay on the App Store version and wait for the update to come through.

That said, good to hear the issue is resolved with v1.28. I’ll close this issue because there’s nothing more I can do, but if you have problems after the update please feel free to tag me here, or you can contact our customer success team at www.Bitwarden.com/contact.

**Comment by PatrickBK** [comment]
Check, thanks and my compliments for how fast handling my problem report went :-)

Met vriendelijke groet/sincerely,

Patrick Bos Kessen

	+31 629 006 722

**Comment by PatrickBK** [comment]
Hi,

It’s September 10th and the update is still not available in the App Store and your direct download function lacks integration with Safari so this way, a fix is rather unpleasantly theoretical.

When can I expect the update to actually be available including all the regulair functionality so on the App Store?

Met vriendelijke groet/sincerely,

Patrick Bos Kessen

	+31 629 006 722

**Comment by eliykat** [comment]
Hi @PatrickBK, sorry about this delay. I'm following it up internally and I'll let you know when I have an update.

**Comment by PatrickBK** [comment]
Hi,

Any info yet? It’s starting to be a real annoyance as I use the letter variants pretty often and a fix should be available but isn’t.

Met vriendelijke groet/sincerely,

Patrick Bos Kessen

	+31 629 006 722

**Comment by cscharf** [comment]
v1.28.2 is now live on the mac app store.
