### ISSUE TITLE
Update continuously offered at Windows start despite being at latest version 

### ISSUE THREAD

**Issue by ComotoJC** [bitwarden/desktop#1423]
### Steps To Reproduce

Steps to reproduce?  Uh. i guess...
1. Start with 1.31 version
2. Restart windows and wait to be prompted for update
3. Respond yes to update installation and restart BW
4. Restart windows and wait to be prompted yet again to install update 
5. Manually check version to see it has not worked
6. Manually install latest version 1.32
7. Start BW and manually check for update and see that "no update available"
8. Restart windows and wait to be prompted yet again to install update despite being on latest version 

### Expected Result

This format for BR is kind of ridiculous for this type of thing which could be explained better in just one box but OK... 

1. Ensure that windows-start update prompt actually installs update if one is available. 
and 
2. Don't prompt for an update if program is already at latest version

### Actual Result

On windows startup for some time now, BW **always** offered to install an update and requests a restart.  
Not only was the windows-start update not working, but now, seems that the version check is returning erroneous status.   

At first it turned out the update process - despite responding properly to all prompts for admin access etc. - was not actually installing the latest update (to 1.32 when I checked) manually downloaded and installed update.  Extremely high number of times I authorized install of the update but it did not install. 

Then after doing manual 1.32 install, on Windows reboot BW still requests to install and restart every time despite being on latest version.  Manually checking for updates returns - as it should - 'no update available'. Yet on next Windows restart i will get prompted again to install an update and restart BW.   

### Additional Context

Version 1.32.0
Shell 16.0.7
Renderer 96.0.4664.110
Node 16.9.1
Architecture x64

### Operating System

Windows

### Operating System Version

10 Pro x64

### Installation method

Direct Download (from bitwarden.com)

### Build Version

See text of bug report

**Comment by chetweewax** [comment]
subbed, I am having the same issue

**Comment by persigio** [comment]
Same

**Comment by dwbit** [comment]
Thanks for the feedback everyone, while this issue is being looked into, can you try using 'install bitwarden for all users' as indicated [here](https://community.bitwarden.com/t/updates-repeat-over-and-over-again/39329).

**Comment by Burgaman** [comment]
same

**Comment by kkrza8** [comment]
I was able to get around the issue by right clicking Bitwarden in the taskbar and selecting Exit. A window popped up requesting administrative privileges to close the program - don't remember the exact wording. It was windows generic "the app is requesting admin privileges". I restarted the program an it stated it was now version 1.32.1.

**Comment by jrschueller** [comment]
> I was able to get around the issue by right clicking Bitwarden in the taskbar and selecting Exit. A window popped up requesting administrative privileges to close the program - don't remember the exact wording. It was windows generic "the app is requesting admin privileges". I restarted the program an it stated it was now version 1.32.1.
> 
> I would also note that during this issue, when I would go to the Help menu and Check for Updates nothing would happen.

My experience is the exact same.

**Comment by EchoDev** [comment]
+1

Can confirm the same issue.

**Comment by RRZZ7** [comment]
Same problem....PLEASE solve it

**Comment by djprmf** [comment]
Also having this issue requestion to update to 1.31 and now again to 1.31.1.

**Comment by Hinton** [comment]
Hi all,

I'm currently looking into this issue but are having difficulties replicating it. I did notice that the updater now gives an option for computer wide and user only which could mean that you have two installs of Bitwarden.

Could someone that is experiencing this issue be willing to check if this is the case?

The two install paths should be

```
C:\Program Files\Bitwarden
```

```
%LocalAppData%\Programs\Bitwarden
```

Right clicking on `Bitwarden.exe` and selecting `Properties`, and navigating to `Details` should specify which version it is.

![image](https://user-images.githubusercontent.com/137855/159913472-19e6e443-5b08-4c0e-96d1-725ecdbfeaa0.png)

If both paths are installed and have different versions, the installer would be triggered when starting the "old" bitwarden application.

**Comment by Hinton** [comment]
@kkrza8 Just to verify, you are still getting the prompts?

**Comment by Hinton** [comment]
A quick update, I've identified an issue where the setup wizard sometimes didn't appear and the upgrade failed. The desktop application would therefore still be on the old version, and prompt for an upgrade again, and repeat. As some people have mentioned, closing the application (by right clicking in the task bar) will also trigger the update flow which seems to behave better.

Another alternative is to download the installer from the website and manually reinstall with the newer version. We will continue to investigate this behavior and hoping to have this resolved by the next release.

Do note however that I haven't been able to replicate the behavior where it still prompts you even on the latest version. If someone is encountering that issue reliably I would appreciate if you could perform the steps described in https://github.com/bitwarden/desktop/issues/1423#issuecomment-1077562089 and let me know the details.

**Comment by Modged** [comment]
> 

Hi I have the issue too, you were right about the differents versions installed... I don't know why or how it happened because..
I am the only user on my computer and never asked for a computer wide installation.
So I have two bitwarden how can I solve this issue which is really annoying I have tried to uninstall and reinstall and it didnt fix the issue
The x:\programfile version :
![bitwarden](https://user-images.githubusercontent.com/47032672/160254430-dc883cea-1524-4141-bf99-82665d9d70e8.png)

An the appdata version : 
![bitwarden2](https://user-images.githubusercontent.com/47032672/160254460-f5a112d7-fe94-4ca2-8f8a-726474bfb926.png)

Thanks a lot for the work you did and are doing :)

**Comment by Hinton** [comment]
Hi @Modged,

Could you try uninstalling it from both directories by running the `Uninstall Bitwarden.exe`? I believe just uninstalling it from `Settings`, would just uninstall a single instance of the app. And then re-install it using the latest installer.

**Comment by assasinxtg** [comment]
I found this folder when I try to fix this issue. Is it safe to delete this?

\AppData\Local\bitwarden-updater

It shows there is a pending update file there and .7z package.

**Comment by rob2009** [comment]
I was having the "install loop" problem as described but tried uninstall>restartPC>reinstall 
That issue is now gone and the app now APPEARS to open, the icon is on the taskbar but when I click the bitwarden screen doesn't appear. 
When I Alt-Tab through running apps it's there but if I stop on the bitwarden mini-image it has no effect.  
I'm currently using https://vault.bitwarden.com/#/vault through Chrome so I can at least access my login credentials but this issue erodes my trust in bitwarden, can I rely on browser access or might that screw up too?

v1.31.1.0 
Win10 21H1 build 19043.1586

**Comment by Modged** [comment]
> Hi @Modged,
> 
> Could you try uninstalling it from both directories by running the `Uninstall Bitwarden.exe`? I believe just uninstalling it from `Settings`, would just uninstall a single instance of the app. And then re-install it using the latest installer.

Hi again :)
It worked running uninstall from the folder.
Thanks you

**Comment by Fhaynes715** [comment]
Was able to resolve this issue: I originally was always selecting to install update for ALL USERS on machine. When selecting this and clicking "OK" it first went through the install process, loading bars, etc. then closed and immediately prompted to install the update again.

Used Task Manager to kill all running instances including background. On next attempt I selected only MY USER. It requested admin access and installed the update successfully this time. Seems to be running OK now and is v. 1.32.1

**Comment by PascalDk** [comment]
+1 
Same issue here.

I tried uninstall/reinstall without any change.

**Comment by TEngelman** [comment]
Just added my 5 cents in https://community.bitwarden.com/t/windows-client-updates-repeat-over-and-over-again/39329/16

**Comment by totallygeekdom** [comment]
I am currently having this issue.

**Comment by Hinton** [comment]
@totallygeekdom please follow the steps in the comment above. This release should have fixed the flow for future updates. Unfortunately current installs on previous versions might still encounter the issue as it uses the old code.
