### ISSUE TITLE
App doesn't ONLY start to the menu bar

### ISSUE THREAD

**Issue by Drjacky** [bitwarden/desktop#752]
## Describe the Bug
I've checked start to the menu bar but, the app still open the window on OS start-up **as well**

## Steps To Reproduce

1. Be sure that the start to menu bar is checked
2. Restart the OS and wait for the OS to boot up
3. You will see the app window will be opened + app icon on the menu bar

## Expected Result

By checking the "Start to menu bar" option, I expect no app window pop up at first runs.

## Actual Result

Despite the "Start to menu bar" option is checked, the app will open both its window and the icon on the menu bar.

## Screenshots or Videos
<img width="423" alt="Screen Shot 2021-03-06 at 09 06 52" src="https://user-images.githubusercontent.com/2296754/110202365-eee65f00-7e5f-11eb-9fc5-4bdc10be557d.png">

## Environment

- Operating system: Mac OS Big Sure 11.2.2
- Build Version: 1.24.5 (513)

## Additional Context
N/A

**Comment by Br3W7h1S** [comment]
I have this exact same issue on Windows 10.  I actually came here to report the same bug, but clearly it isn't just me.  The program launches on start, but I am presented with the application window containing simply a black, blank screen, which is opened as a maximised window.  If I close the window and then click on the tray icon the application opens again and then presents the login boxes.  I have tried rebooting and turning the options on and off again, but no joy.

OS details:

Edition	Windows 10 Pro
Version	20H2
Installed on	‎07/‎11/‎2020
OS build	19042.867

Bitwarden version: 1.25.0

**Comment by Drjacky** [comment]
@Br3W7h1S My issue has been solved with this configuration:  
<img width="496" alt="Screen Shot 2021-03-14 at 16 01 23" src="https://user-images.githubusercontent.com/2296754/111075147-87bf4f00-84de-11eb-9530-9c3520704819.png">

**Comment by Br3W7h1S** [comment]
Thanks @Drjacky, much appreciated, but doesn't this just essentially mean Bitwarden simply will not launch after logging into your OS?

**Comment by Drjacky** [comment]
@Br3W7h1S For me, It runs but, there is no need to enter your password or do biometric unlocking.

**Comment by kendratodd** [comment]
I've not been able to reproduce this one testing against Big Sur MacOS 11.2.3, nor against a Virtual Machine running Windows 10. @Br3W7h1S - are you still seeing the blank app window you mentioned when your machine boots up?

**Comment by Br3W7h1S** [comment]
Hi Kendra.  Yes, I'm afraid it still happens.  I've turned off the option to launch at boot, which has stopped the window popping up when I boot the OS, but that obviously doesn't solve the problem, as the application now needs to be manually started.

________________________________

**Comment by kendratodd** [comment]
Thanks @Br3W7h1S - this has the sniff of a possible electron problem. We did issue a follow up [release](https://github.com/bitwarden/desktop/releases/tag/v1.25.1) containing some electron bug fixes (v 1.25.1). Just to confirm, have you been able to to update to that latest version?

**Comment by Br3W7h1S** [comment]
> 
> 
> Thanks @Br3W7h1S - this has the sniff of a possible electron problem. We did issue a follow up [release](https://github.com/bitwarden/desktop/releases/tag/v1.25.1) containing some electron bug fixes (v 1.25.1). Just to confirm, have you been able to to update to that latest version?

Thanks @kendratodd, and yes, I have just checked and I am running 1.25.1.  I believe the issue started since the update, but cannot confirm for certain as I didn't note down the date at the time of first occurance.  It was definitely around the time (roughly) the update was pushed out, though.
